# Generated by Django 3.0 on 2020-06-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrik',
            fields=[
                ('id_distrik', models.AutoField(primary_key=True, serialize=False)),
                ('nama_distrik', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kampung',
            fields=[
                ('id_kampung', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kampung', models.CharField(max_length=30)),
                ('distrik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Distrik')),
            ],
        ),
    ]
